<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AppShellPackageRoot Condition="'$(AppShellPackageRoot)' == ''">$(MSBuildThisFileDirectory)..\..\..\2026-023-HistoryVulcan\z-Package-AppShell</AppShellPackageRoot>
    <AppShellHostRoot Condition="'$(AppShellHostRoot)' == ''">$(AppShellPackageRoot)\host</AppShellHostRoot>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AppShell.Core">
      <HintPath>$(AppShellHostRoot)\AppShell.Core.dll</HintPath>
    </Reference>
    <Reference Include="AppShell.Services">
      <HintPath>$(AppShellHostRoot)\AppShell.Services.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
