<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AppShellPackageRoot Condition="'$(AppShellPackageRoot)' == ''">C:\OneHistory\OneHistory-Projects\2026-023-AppShell\z-Package-AppShell</AppShellPackageRoot>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AppShell.Core">
      <HintPath>$(AppShellPackageRoot)\host\AppShell.Core.dll</HintPath>
    </Reference>
    <Reference Include="AppShell.Services">
      <HintPath>$(AppShellPackageRoot)\host\AppShell.Services.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
