<Project>
  <PropertyGroup>
    <HistoryDianaVersion>1.0.0</HistoryDianaVersion>
    <VersionPrefix>$(HistoryDianaVersion)</VersionPrefix>
    <Version>$(HistoryDianaVersion)</Version>
    <AssemblyVersion>$(HistoryDianaVersion).0</AssemblyVersion>
    <FileVersion>$(HistoryDianaVersion).0</FileVersion>
    <InformationalVersion>$(HistoryDianaVersion)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
