<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- 发布成单文件 exe，模块目录 Modules 放在 exe 旁边 -->
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>false</SelfContained>
		<DebugType>None</DebugType>
	</PropertyGroup>

</Project>
