<Project>
  <PropertyGroup>
    <OneHistoryStudioVersion>2.9.1</OneHistoryStudioVersion>
    <VersionPrefix>$(OneHistoryStudioVersion)</VersionPrefix>
    <Version>$(OneHistoryStudioVersion)</Version>
    <AssemblyVersion>$(OneHistoryStudioVersion).0</AssemblyVersion>
    <FileVersion>$(OneHistoryStudioVersion).0</FileVersion>
    <InformationalVersion>$(OneHistoryStudioVersion)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
